[package]
name = "ruby"
version = "0.1.0"
edition = "2024"
authors = ["Abhinav"]

[dependencies]

[dev-dependencies]
criterion = "0.7.0"

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[[bench]]
name = "benchmark"
harness = false


